### ISSUE TITLE
PIP install failure

### ISSUE THREAD

**Issue by smithzc** [oracle/python-oracledb#158]
I regularly build oracledb weekly and have encountered an issue this week.   Setup is straight forward :
sudo yum install python3-devel
pip3 install oracledb

I have tested this using OEL7 and OEL8 across most hardware configurations on OCI and am having the same issue in each environment.

During the PIP build here is the error I'm encountering:

---- Output below (sorry formatting is messed up for copy/paste -----

```
warning: src/oracledb/impl/thin/network_services.pyx:65:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
    building 'oracledb.thin_impl' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c src/oracledb/thin_impl.c -o build/temp.linux-x86_64-3.6/src/oracledb/thin_impl.o
    gcc -pthread -shared -Wl,-z,relro -Wl,-z,now -g -Wl,-z,relro -Wl,-z,now -g build/temp.linux-x86_64-3.6/src/oracledb/thin_impl.o -L/usr/lib64 -lpython3.6m -o build/lib.linux-x86_64-3.6/oracledb/thin_impl.cpython-36m-x86_64-linux-gnu.so
    Compiling src/oracledb/thick_impl.pyx because it changed.
    [1/1] Cythonizing src/oracledb/thick_impl.pyx

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                session_callback_bytes = params.session_callback.encode()
                create_params.plsqlFixupCallback = session_callback_bytes
                create_params.plsqlFixupCallbackLength = \
                        <uint32_t> len(session_callback_bytes)
            if params.access_token_callback is not None:
                create_params.accessTokenCallback = _token_callback_handler
                                                    ^
    ------------------------------------------------------------

    src/oracledb/impl/thick/pool.pyx:116:48: Cannot assign type 'int (void *, dpiAccessToken *) except? -1 nogil' to 'dpiAccessTokenCallback'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            params.portNumber = self.port
            params.timeout = self.timeout
            params.name = name_buf.ptr
            params.nameLength = name_buf.length
            if self.callback is not None:
                params.callback = _callback_handler
                                  ^
    ------------------------------------------------------------

    src/oracledb/impl/thick/subscr.pyx:159:30: Cannot assign type 'void (void *, dpiSubscrMessage *) except * nogil' to 'dpiSubscrCallback'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1n4gr6zh/oracledb/setup.py", line 95, in <module>
        extra_compile_args=extra_compile_args)
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.6/distutils/command/install.py", line 556, in run
        self.run_command('build')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "/tmp/pip-build-1n4gr6zh/oracledb/.eggs/Cython-3.0.0b1-py3.6.egg/Cython/Distutils/build_ext.py", line 123, in build_extension
        ext,force=self.force, quiet=self.verbose == 0, **options
      File "/tmp/pip-build-1n4gr6zh/oracledb/.eggs/Cython-3.0.0b1-py3.6.egg/Cython/Build/Dependencies.py", line 1134, in cythonize
        cythonize_one(*args)
      File "/tmp/pip-build-1n4gr6zh/oracledb/.eggs/Cython-3.0.0b1-py3.6.egg/Cython/Build/Dependencies.py", line 1301, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: src/oracledb/thick_impl.pyx

    ----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1n4gr6zh/oracledb/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bprfl3fp-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-1n4gr6zh/oracledb/`

**Comment by cjbj** [comment]
- Fundamentally you should look at moving from Python 3.6 to a newer version of Python.
- Update `pip` before installing: `pip3 install pip --upgrade`
- There are RPMs on yum.oracle.com for OL7 & 8 that work with Python 3.6. 
   ```
   sudo dnf -y install oraclelinux-developer-release-el8
   sudo dnf -y install python3-oracledb
   ```
   or
   ```
   sudo yum -y install oraclelinux-developer-release-el7
   sudo yum -y install python3-oracledb
   ```
   I'm still working with the Linux team on updates

**Comment by cjbj** [comment]
I haven't seen that with my images, but its good to have it on record.  Thanks for sharing.  I'll close this.
