### ISSUE TITLE
Getting DPI-1047: Cannot locate a 64-bit Oracle Client library

### ISSUE THREAD

**Issue by shaik-jafar6** [oracle/python-oracledb#243]
-->

1. What versions are you using?
    oracledb version 1.4.1

2. Is it an error or a hang or a crash?
    error

4. What error(s) or behavior you are seeing?
    Traceback (most recent call last):
  File "/application/INFA/server/infa_shared/Scripts/test.py", line 76, in <module>
    table_names = get_list_tables(schema_name)  # Add more table names as needed
  File "/application/INFA/server/infa_shared/Scripts/test.py", line 63, in get_list_tables
    oracledb.init_oracle_client('/u01/oracle/product/12.0.1/client_64/lib')
  File "src/oracledb/impl/thick/utils.pyx", line 476, in oracledb.thick_impl.init_oracle_client
  File "src/oracledb/impl/thick/utils.pyx", line 500, in oracledb.thick_impl.init_oracle_client
  File "src/oracledb/impl/thick/utils.pyx", line 421, in oracledb.thick_impl._raise_from_info
oracledb.exceptions.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "/u01/oracle/product/12.0.1/client_64/lib/libclntsh.so: cannot open shared object file: No such file or directory". See https://python-oracledb.readthedocs.io/en/latest/user_guide/initialization.html for help

5. Does your application call init_oracle_client()?
  yes

6. Include a runnable Python script that shows the problem.
   oracledb.init_oracle_client('u01/oracle/product/12.0.1/client_64/lib')

Running the code in linux system. Not able to figure out the solution. Please do need the helpful
![image](https://github.com/oracle/python-oracledb/assets/112137448/766d12ac-027b-4e2e-8cb0-77f63b3f0412)

**Comment by cjbj** [comment]
Review the troubleshooting doc https://python-oracledb.readthedocs.io/en/latest/user_guide/troubleshooting.html#dpi-1047 and https://python-oracledb.readthedocs.io/en/latest/user_guide/initialization.html

**Comment by shaik-jafar6** [comment]
Below are the things in linux server which informatica is referring
[Friday 8:03 AM] Khanna, Nitin

ORACLE_BASE=/u01/oracle

ORACLE_HOME=$ORACLE_BASE/product/12.1.0/client_64

TNS_ADMIN=$ORACLE_HOME/network/admin

LD_LIBRARY_PATH=$ORACLE_HOME/lib:$LD_LIBRARY_PATH

I did tried checking the logs by keeping the export level to DPI_DEBUG_LEVEL=64 but i am seeing same issue. Can you guide how can i connect based on above variables set

**Comment by cjbj** [comment]
Please read the doc: on Linux you should not pass a path to init_oracle_client().

Also consider removing the call to init_oracle_client() - again read the doc about what this does.

**Comment by shaik-jafar6** [comment]
Christopher i read the docs and if i am not providing the path to the init_oracle_client() it's looking for the oracle library at python directory as shown below. 

![image](https://github.com/oracle/python-oracledb/assets/112137448/3bf61f4b-fca3-4a7e-93ba-bc73debdb4a6)

**Comment by cjbj** [comment]
Did you try removing the call to init_oracle_client()?

PS don't paste screenshots- not everyone can view them.

**Comment by shaik-jafar6** [comment]
If i remove the below code snippet from my script it goes for thin mode. In case of thin mode if i have 3 tables it's working fine for 2 tables and it's providing me internal error for third table. 
I tried similar thing on my local where i am able to read all three tables using thick mode and in case of thin mode i am facing internal error for few tables. I am planning to run in thick mode but for thick mode the documentation says to have a call to init_oracle_client()?

**Comment by cjbj** [comment]
What's the  internal error for third table?  What is the SQL to create that table?  What is the database version?

**Comment by anthony-tuininga** [comment]
Closing - no activity
