### ISSUE TITLE
Connection fails with thin mode and SQLNET.ALLOW_WEAK_CRYPTO_CLIENTS=FALSE

### ISSUE THREAD

**Issue by slords** [oracle/python-oracledb#296]
1. What versions are you using?

oracle.se2: 19.21
platform.platform: macOS-14.3.1-arm64-arm-64bit
sys.maxsize > 2**32: True
platform.python_version: 3.11.7
oracledb.__version__: 2.0.1

2. Is it an error or a hang or a crash?

Error when SQLNET.ALLOW_WEAK_CRYPTO_CLIENTS=FALSE.  If this option is set to TRUE (the default) then the connection succeeds.  Setting this to false enables stronger enforcement of encryption protocols.  Normally setting this to FALSE requires 19.12 client libraries or newer (July 2021 or newer libraries).

3. What error(s) or behavior you are seeing?

Traceback (most recent call last):
  File "src/oracledb/impl/thin/transport.pyx", line 300, in oracledb.thin_impl.Transport.read_packet
ConnectionResetError: [Errno 54] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/oracledb/connection.py", line 1134, in connect
    return conn_class(dsn=dsn, pool=pool, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/oracledb/connection.py", line 523, in __init__
    impl.connect(params_impl)
  File "src/oracledb/impl/thin/connection.pyx", line 449, in oracledb.thin_impl.ThinConnImpl.connect
  File "src/oracledb/impl/thin/connection.pyx", line 445, in oracledb.thin_impl.ThinConnImpl.connect
  File "src/oracledb/impl/thin/connection.pyx", line 411, in oracledb.thin_impl.ThinConnImpl._connect_with_params
  File "src/oracledb/impl/thin/connection.pyx", line 392, in oracledb.thin_impl.ThinConnImpl._connect_with_description
  File "src/oracledb/impl/thin/connection.pyx", line 365, in oracledb.thin_impl.ThinConnImpl._connect_with_address
  File "src/oracledb/impl/thin/protocol.pyx", line 284, in oracledb.thin_impl.Protocol._connect_phase_two
  File "src/oracledb/impl/thin/protocol.pyx", line 386, in oracledb.thin_impl.Protocol._process_message
  File "src/oracledb/impl/thin/protocol.pyx", line 364, in oracledb.thin_impl.Protocol._process_message
  File "src/oracledb/impl/thin/protocol.pyx", line 436, in oracledb.thin_impl.Protocol._receive_packet
  File "src/oracledb/impl/thin/packet.pyx", line 588, in oracledb.thin_impl.ReadBuffer.wait_for_packets_sync
  File "src/oracledb/impl/thin/transport.pyx", line 302, in oracledb.thin_impl.Transport.read_packet
  File "/opt/homebrew/lib/python3.11/site-packages/oracledb/errors.py", line 162, in _raise_err
    raise exc_type(_Error(message)) from cause
oracledb.exceptions.DatabaseError: DPY-4011: the database or network closed the connection
[Errno 54] Connection reset by peer
Help: https://python-oracledb.readthedocs.io/en/latest/user_guide/troubleshooting.html#dpy-4011

4. Does your application call init_oracle_client()?

No, there is no thick client for Mac M2 machines.  I need to use the thin client.

5. Include a runnable Python script that shows the problem.

```
import oracledb
connection = oracledb.connect(user='user', password='pass', dsn='(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=host)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=service)))')
import oracledb
```

**Comment by anthony-tuininga** [comment]
This is a known restriction, unfortunately. See #94. It has been reported to management and I will report this request as well.
