### ISSUE TITLE
Using pyinstaller to compile a simple code with oracledb throws an error in the executable file

### ISSUE THREAD

**Issue by horstrand** [oracle/python-oracledb#31]
I am trying to compile a test code that simply connects to an oracle datable using pyinstaller.
I'm doing it with the --onefile option as shown below:

pyinstaller test_oracle.py --onefile 

When I later run the executable, at first I got a few errors, just some modules that were missing ('secrets', 'ssl', 'getpass', 'cryptography'). I fixed it with the option --hidden-import from pyinstaller.

After fixing that, a new error showed up, which I have not been able to fix:

Traceback (most recent call last):
  File "test_oracle.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "oracledb\__init__.py", line 38, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "oracledb\connection.py", line 39, in <module>
  File "src\oracledb\impl/thin/crypto.pyx", line 35, in init oracledb.thin_impl
ImportError: cannot import name pbkdf2
[18124] Failed to execute script 'test_oracle_sac' due to unhandled exception!

I have tried importing the module in different ways and it still does not work.

Any help would be appreciated!

1. What versions are you using?

oracledb==1.0.1
python 3.10.0
pyinstaller==5.1

**Comment by horstrand** [comment]
Yes, it worked very well!
Thanks for the support

**Comment by cjbj** [comment]
Also see https://github.com/oracle/python-oracledb/discussions/57 for another solution.

**Comment by LunRod** [comment]
Hello everyone, I had the same problem exposed, thanks to this chain of messages I managed to solve it.

However, when I run the .exe and do a query it gives me an error.
It says that "data" is not defined and it is where I am storing the query made.
