### ISSUE TITLE
init_oracle_client not support non-ASCII path on Windows

### ISSUE THREAD

**Issue by PaleNeutron** [oracle/python-oracledb#379]
1. What versions are you using?

    platform.platform: Windows-10-10.0.19043-SP0
    sys.maxsize > 2**32: True
    platform.python_version: 3.12.3
    oracledb.__version__: 2.3.0

2. Is it an error or a hang or a crash?

yes

3. What error(s) or behavior you are seeing?

```
Traceback (most recent call last):
  File "d:\win_projects\tmp\oracle中文路径测试\venv\Lib\site-packages\amdb\dbconn.py", line 28, in get_engine
    oracledb.init_oracle_client(*args)
  File "src\\oracledb\\impl/thick/utils.pyx", line 505, in oracledb.thick_impl.init_oracle_client
  File "src\\oracledb\\impl/thick/utils.pyx", line 530, in oracledb.thick_impl.init_oracle_client
  File "src\\oracledb\\impl/thick/utils.pyx", line 457, in oracledb.thick_impl._raise_from_info
oracledb.exceptions.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found". See https://python-oracledb.readthedocs.io/en/latest/user_guide/initialization.html for help
```

4. Does your application call init_oracle_client()?

yes

5. Include a runnable Python script that shows the problem.

```
import oracledb

oracledb.init_oracle_client("中文路径测试/instantclient_23_4")
```

**Comment by cjbj** [comment]
Dup of https://github.com/oracle/python-oracledb/issues/255 which is an OS issue.
