### ISSUE TITLE
thick mode connect isn't honoring TNS_ADMIN or using ldap connection

### ISSUE THREAD

**Issue by slords** [oracle/python-oracledb#398]
1. What versions are you using?

platform.platform: macOS-15.0-arm64-arm-64bit
sys.maxsize > 2**32: True
platform.python_version: 3.12.6
oracledb.__version__: 2.4.1

2. Is it an error or a hang or a crash?

Error

3. What error(s) or behavior you are seeing?

When trying to connect to a database I'm getting the following error:

$ env | grep -E 'ORA|TNS|PATH'
TNS_ADMIN=/opt/oracle
PATH=/opt/oracle/instantclient_23_3:...
INFOPATH=/opt/homebrew/share/info:
ORACLE_HOME=/opt/oracle/instantclient_23_3

$ python test.py
Traceback (most recent call last):
  File "/Users/slords/test.py", line 8, in <module>
    c=oracledb.connect(user=user, password=password, dsn=dsn)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slords/.venv/lib/python3.12/site-packages/oracledb/connection.py", line 1169, in connect
    return conn_class(dsn=dsn, pool=pool, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slords/.venv/lib/python3.12/site-packages/oracledb/connection.py", line 554, in __init__
    impl.connect(params_impl, pool_impl)
  File "src/oracledb/impl/thick/connection.pyx", line 494, in oracledb.thick_impl.ThickConnImpl.connect
  File "src/oracledb/impl/thick/utils.pyx", line 446, in oracledb.thick_impl._raise_from_info
oracledb.exceptions.DatabaseError: ORA-12154: Cannot connect to database. Could not find alias whse_dev in /opt/oracle/instantclient_23_3/network/admin/tnsnames.ora.
Help: https://docs.oracle.com/error-help/db/ora-12154/

If I run the same connect using sqlplus it connects fine to the database.  I've got sqlnet.ora and ldap.ora in /opt/oracle. We don't use tnsnames.ora and that file has never existed in any of our installs.

4. Does your application call init_oracle_client()?

Yes

5. Include a runnable Python script that shows the problem.

$ cat test.py
import oracledb
oracledb.init_oracle_client(lib_dir='/opt/oracle/instantclient_23_3')

user='user'
password='pass'
dsn='ldap_alias'

c=oracledb.connect(user=user, password=password, dsn=dsn)

**Comment by cjbj** [comment]
A couple of things to try:

- unset ORACLE_HOME - this should never be set when using Instant Client
- move the sqlnet.ora & ldap.ora files to default location /opt/oracle/instantclient_23_3/network/admin/ and also unset TNS_ADMIN
- Enable SQL*Net tracing and check how it is loading the sqlnet.ora / ldap.ora files.  I create $HOME/.sqlnet.ora (note the leading period) with:

**Comment by anthony-tuininga** [comment]
Can you confirm that both SQL*Plus and python-oracledb are using the same Oracle Client (/opt/oracle/instantclient_23_3)?

**Comment by slords** [comment]
Yes I have openldap installed.  Setting DYLD_PRINT_LIBRARIES=YES does not show it trying to load openldap.

```
$ brew list | grep -i ldap
openldap
$ DYLD_PRINT_LIBRARIES=YES python test.py 2>&1 | grep -i ldap
dyld[13208]: <0F91824C-19C9-3A36-AA83-E2CFE0FF5FB3> /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP
dyld[13208]: <0F91824C-19C9-3A36-AA83-E2CFE0FF5FB3> /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP
oracledb.exceptions.DatabaseError: ORA-12154: Cannot connect to database. Could not find alias ldap_alias in /opt/oracle/instantclient_23_3/network/admin/tnsnames.ora.
```

**Comment by sreguna** [comment]
If possible can you uninstall openldap and run the application? Oracle client libraries come bundled with its own ldap library and there could be some interference with openldap. Could be worth a shot.

**Comment by slords** [comment]
There are not changes between having openldap installed and not.

**Comment by slords** [comment]
Yes

**Comment by cjbj** [comment]
I wonder if this still reproduces with the newer 23.26.1.0.0 client for macOS ARM (https://www.oracle.com/database/technologies/instant-client/macos-arm64-downloads.html)

**Comment by anthony-tuininga** [comment]
@slords, can you check?
