### ISSUE TITLE
InvalidSwitchError - Invalid switch into Greenlet OR BlockingSwitchOutError

### ISSUE THREAD

**Issue by lironshurgi** [oracle/python-oracledb#42]
1. What versions are you using?
platform.platform: Linux-4.14.186-146.268.amzn2.x86_64-x86_64-with-glibc2.31
sys.maxsize > 2**32: True
platform.python_version: 3.9.10
oracledb.version: 1.0.2
sqlalchemy.version: 1.4.35
gevent.version: 21.12.0
gunicorn.version: 20.1.0
oracle database version: Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0

3. Is it an error or a hang or a crash?
Crash

4. What error(s) or behavior you are seeing?
Gunicorn (gevent workers) requests failed with error `InvalidSwitchError`
```
2022-07-31 11:58:56,377 ERROR sqlalchemy.pool.impl.QueuePool Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/project_venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/project_venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/project_venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 682, in do_rollback
    dbapi_connection.rollback()
  File "/usr/local/project_venv/lib/python3.9/site-packages/oracledb/connection.py", line 634, in rollback
    self._impl.rollback()
  File "src/oracledb/impl/thin/connection.pyx", line 399, in oracledb.thin_impl.ThinConnImpl.rollback
  File "src/oracledb/impl/thin/protocol.pyx", line 301, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 302, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 262, in oracledb.thin_impl.Protocol._process_message
  File "src/oracledb/impl/thin/protocol.pyx", line 240, in oracledb.thin_impl.Protocol._process_message
  File "src/oracledb/impl/thin/protocol.pyx", line 308, in oracledb.thin_impl.Protocol._receive_packet
  File "src/oracledb/impl/thin/buffer.pyx", line 1092, in oracledb.thin_impl.ReadBuffer.receive_packet
  File "src/oracledb/impl/thin/buffer.pyx", line 427, in oracledb.thin_impl.ReadBuffer._receive_packet_helper
  File "src/oracledb/impl/thin/buffer.pyx", line 291, in oracledb.thin_impl.ReadBuffer._get_data_from_socket
  File "/usr/local/project_venv/lib/python3.9/site-packages/gevent/_socketcommon.py", line 693, in recv_into
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 304, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 57, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
gevent.exceptions.InvalidSwitchError: Invalid switch into <Greenlet at 0x7fa41355d480: _handle_and_close_when_done(functools.partial(<bound method GeventWorker.handl, <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket at 0x7fa41855c820 object,)>: got None (expected <gevent._gevent_c_waiter.Waiter object at 0x7fa40b4f1cc0>; waiting on <Hub '' at 0x7fa4364b4340 epoll default pending=0 ref=9 fileno=6 resolver=<gevent.resolver.thread.Resolver at 0x7fa42f8e9760 pool=<ThreadPool at 0x7fa42f8ebb20 tasks=0 size=2 maxsize=10 hub=<Hub at 0x7fa4364b4340 thread_ident=0x7fa43a301740>>> threadpool=<ThreadPool at 0x7fa42f8ebb20 tasks=0 size=2 maxsize=10 hub=<Hub at 0x7fa4364b4340 thread_ident=0x7fa43a301740>> thread_ident=0x7fa43a301740> with <io at 0x7fa40bb6d8c0 native=0x7fa40bb6d900 fd=27 events=READ active callback=<bound method Waiter.switch of <gevent._gevent_c_waiter.Waiter object at 0x7fa40b4f1cc0>> args=(<gevent._gevent_c_waiter.Waiter object at 0x7fa40b4f1cc0>,)>)
```

I got a few of this error as well (not sure if this is related but seems related)
```
2022-07-31 17:35:35,961 ERROR sqlalchemy.pool.impl.QueuePool Exception during reset or similar
Traceback (most recent call last):
File "src/oracledb/impl/thin/protocol.pyx", line 240, in oracledb.thin_impl.Protocol._process_message
File "src/oracledb/impl/thin/protocol.pyx", line 308, in oracledb.thin_impl.Protocol._receive_packet
File "src/oracledb/impl/thin/buffer.pyx", line 1092, in oracledb.thin_impl.ReadBuffer.receive_packet
File "src/oracledb/impl/thin/buffer.pyx", line 427, in oracledb.thin_impl.ReadBuffer._receive_packet_helper
File "src/oracledb/impl/thin/buffer.pyx", line 291, in oracledb.thin_impl.ReadBuffer._get_data_from_socket
File "/usr/local/project_venv/lib/python3.9/site-packages/gevent/_socketcommon.py", line 693, in recv_into
self._wait(self._read_event)
File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
File "src/gevent/_hub_primitives.py", line 304, in gevent._gevent_c_hub_primitives._primitive_wait
File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
File "src/gevent/_greenlet_primitives.py", line 64, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
File "src/gevent/_greenlet_primitives.py", line 67, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
File "src/gevent/_greenlet_primitives.py", line 68, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
gevent.exceptions.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/project_venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 739, in _finalize_fairy
fairy._reset(pool)
File "/usr/local/project_venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 988, in _reset
pool._dialect.do_rollback(self)
File "/usr/local/project_venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 682, in do_rollback
dbapi_connection.rollback()
File "/usr/local/project_venv/lib/python3.9/site-packages/oracledb/connection.py", line 634, in rollback
self._impl.rollback()
File "src/oracledb/impl/thin/connection.pyx", line 399, in oracledb.thin_impl.ThinConnImpl.rollback
File "src/oracledb/impl/thin/protocol.pyx", line 301, in oracledb.thin_impl.Protocol._process_single_message
File "src/oracledb/impl/thin/protocol.pyx", line 302, in oracledb.thin_impl.Protocol._process_single_message
File "src/oracledb/impl/thin/protocol.pyx", line 261, in oracledb.thin_impl.Protocol._process_message
File "src/oracledb/impl/thin/protocol.pyx", line 344, in oracledb.thin_impl.Protocol._reset
File "src/oracledb/impl/thin/buffer.pyx", line 1092, in oracledb.thin_impl.ReadBuffer.receive_packet
File "src/oracledb/impl/thin/buffer.pyx", line 427, in oracledb.thin_impl.ReadBuffer._receive_packet_helper
File "src/oracledb/impl/thin/buffer.pyx", line 291, in oracledb.thin_impl.ReadBuffer._get_data_from_socket
File "/usr/local/project_venv/lib/python3.9/site-packages/gevent/_socketcommon.py", line 693, in recv_into
self._wait(self._read_event)
File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
File "src/gevent/_hub_primitives.py", line 304, in gevent._gevent_c_hub_primitives._primitive_wait
File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
File "src/gevent/_greenlet_primitives.py", line 64, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
File "src/gevent/_greenlet_primitives.py", line 67, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
File "src/gevent/_greenlet_primitives.py", line 68, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
gevent.exceptions.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
```

5. Does your application call init_oracle_client()?
No

6. Include a runnable Python script that shows the problem.
As far as I can see, this is very rare - 1 request failed among thousands who succeeded (for a few hours test) - hence I can't reproduce it for now

**Comment by anthony-tuininga** [comment]
I'm not sure how greenlets exactly work and whether there is a bug in that code, or in the interaction with SQLAlchemy, or in the way that python-oracledb (thin) works. If you are able to supply a standalone script that demonstates the issue -- even if it regularly takes hours to reproduce -- that would be helpful.

**Comment by cjbj** [comment]
Closing - requested info was not provided
